trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

parameters:
  - name: dev
    type: boolean
    default: true
  - name: stage
    type: boolean
    default: false
  - name: test
    type: boolean
    default: false
  - name: prod
    type: boolean
    default: false

resources:
  repositories:
    - repository: PipelineTemplates
      type: git
      name: Devops-CoE/PipelineTemplates
      ref: refs/heads/main

stages:
  - stage: deploy_dev
    displayName: Deploy Dev
    condition: eq('${{ parameters.dev }}', 'true')
    jobs:
      - template: templates/terraform/deploy-terraform.yaml
        parameters:
          env: dev
          adoEnv: 'dev-env-vars'
          pool: 
            name: 'MyAgent'
            vmImage: 'ubuntu-latest'
          serviceConnection: 'dev-service-connection'

  - stage: deploy_stage
    displayName: Deploy Stage
    condition: eq('${{ parameters.stage }}', 'true')
    jobs:
      - template: templates/terraform/deploy-terraform.yaml
        parameters:
          env: stage
          adoEnv: 'stage-env-vars'
          pool: 
            name: 'MyAgent'
            vmImage: 'ubuntu-latest'
          serviceConnection: 'stage-service-connection'

  - stage: deploy_test
    displayName: Deploy Test
    condition: eq('${{ parameters.test }}', 'true')
    jobs:
      - template: templates/terraform/deploy-terraform.yaml
        parameters:
          env: test
          adoEnv: 'test-env-vars'
          pool: 
            name: 'MyAgent'
            vmImage: 'ubuntu-latest'
          serviceConnection: 'test-service-connection'

  - stage: deploy_prod
    displayName: Deploy Prod
    condition: eq('${{ parameters.prod }}', 'true')
    jobs:
      - template: templates/terraform/deploy-terraform.yaml
        parameters:
          env: prod
          adoEnv: 'prod-env-vars'
          pool: 
            name: 'Azure Pipelines'
            vmImage: 'ubuntu-latest'
          serviceConnection: 'prod-service-connection' 