trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

parameters:
  - name: dev
    type: boolean
    default: true

resources:
  repositories:
    - repository: PipelineTemplates
      type: git
      name: Devops-CoE/PipelineTemplates
      ref: refs/heads/main

stages:
  - stage: deploy_dev
    displayName: Deploy Dev
    condition: and(succeeded(), ${{ parameters.dev }})
    jobs:
      - template: templates/jobs-deploy.yaml
        parameters:
          env: dev
          adoEnv: dev
          pool: myaget
          serviceConnection: myconection