parameters:
  - name: env
    type: string
  - name: adoEnv
    type: string
    default: ''
  - name: pool
    type: string
  - name: serviceConnection
    type: string

jobs:
  - deployment: terraform
    displayName: Terraform - ${{ parameters.env }}
    environment: ${{ parameters.adoEnv }}
    pool:
      name: ${{ parameters.pool }}
      demands:
        - agent.name -equals agent
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - template: terraform/deploy-terraform.yaml
              parameters:
                adoSubscriptionEndpoint: ${{ parameters.serviceConnection }}
                rootDirectory: iac
                environmentType: ${{ parameters.env }}
                additionalVariables: -var-file="env/${{ parameters.env }}/main.tfvars"
                terraformVersion: "1.7.4"
                publishArtifact: true
                parseOutputs: true
                